/// Lockfile generation and verification for Forge build system.
///
/// The lockfile (`forge.lock`) records the exact resolved versions, sources,
/// and content hashes of every dependency so that builds are reproducible
/// across machines and over time.

use serde::{Deserialize, Serialize};
use std::path::Path;
use std::fs;

// ── Public types ────────────────────────────────────────────────────

/// The full lockfile structure.
#[derive(Debug, Clone)]
pub struct Lockfile {
    pub metadata: LockfileMetadata,
    pub packages: Vec<LockedPackage>,
}

#[derive(Debug, Clone)]
pub struct LockfileMetadata {
    pub forge_version: String,
    pub resolved_at: String, // ISO 8601
}

#[derive(Debug, Clone)]
pub struct LockedPackage {
    pub name: String,
    pub version: String,
    pub source: String, // "registry", "git+url@rev", "path+/local/path"
    pub content_hash: String, // sha256:...
    pub artifact_hash: Option<String>,
    pub capabilities: Vec<String>,
    pub dependencies: Vec<String>, // names of deps
}

/// Describes a single stale dependency detected by `check_staleness`.
#[derive(Debug)]
pub enum StaleDep {
    /// Dep in forge.toml but not in lockfile.
    Missing { name: String, range: String },
    /// Dep in lockfile but not in forge.toml.
    Extra { name: String },
    /// Version range changed between forge.toml and lockfile.
    RangeChanged {
        name: String,
        old_range: String,
        new_range: String,
    },
}

// ── Serde helpers (private) ─────────────────────────────────────────

#[derive(Deserialize, Serialize)]
struct LockfileToml {
    metadata: MetadataToml,
    #[serde(default)]
    package: Vec<PackageToml>,
}

#[derive(Deserialize, Serialize)]
struct MetadataToml {
    forge_version: String,
    resolved_at: String,
}

#[derive(Deserialize, Serialize)]
struct PackageToml {
    name: String,
    version: String,
    source: String,
    content_hash: String,
    artifact_hash: Option<String>,
    #[serde(default)]
    capabilities: Vec<String>,
    #[serde(default)]
    dependencies: Vec<String>,
}

// ── Lockfile impl ───────────────────────────────────────────────────

impl Lockfile {
    /// Parse a `forge.lock` file from its TOML content.
    pub fn parse(content: &str) -> Result<Self, String> {
        let toml_val: LockfileToml =
            toml::from_str(content).map_err(|e| format!("invalid lockfile TOML: {}", e))?;

        let metadata = LockfileMetadata {
            forge_version: toml_val.metadata.forge_version,
            resolved_at: toml_val.metadata.resolved_at,
        };

        let packages = toml_val
            .package
            .into_iter()
            .map(|p| LockedPackage {
                name: p.name,
                version: p.version,
                source: p.source,
                content_hash: p.content_hash,
                artifact_hash: p.artifact_hash,
                capabilities: p.capabilities,
                dependencies: p.dependencies,
            })
            .collect();

        Ok(Lockfile { metadata, packages })
    }

    /// Serialize to a deterministic TOML string.
    pub fn to_toml(&self) -> String {
        let mut out = String::new();
        out.push_str("# This file is auto-generated by forge. Do not edit.\n\n");
        out.push_str("[metadata]\n");
        out.push_str(&format!(
            "forge_version = \"{}\"\n",
            self.metadata.forge_version
        ));
        out.push_str(&format!(
            "resolved_at = \"{}\"\n",
            self.metadata.resolved_at
        ));
        out.push('\n');

        // Sort packages by name for deterministic output
        let mut sorted = self.packages.clone();
        sorted.sort_by(|a, b| a.name.cmp(&b.name));

        for pkg in &sorted {
            out.push_str("[[package]]\n");
            out.push_str(&format!("name = \"{}\"\n", pkg.name));
            out.push_str(&format!("version = \"{}\"\n", pkg.version));
            out.push_str(&format!("source = \"{}\"\n", pkg.source));
            out.push_str(&format!("content_hash = \"{}\"\n", pkg.content_hash));
            if let Some(ref ah) = pkg.artifact_hash {
                out.push_str(&format!("artifact_hash = \"{}\"\n", ah));
            }
            if !pkg.capabilities.is_empty() {
                let caps: Vec<String> =
                    pkg.capabilities.iter().map(|c| format!("\"{}\"", c)).collect();
                out.push_str(&format!("capabilities = [{}]\n", caps.join(", ")));
            }
            if !pkg.dependencies.is_empty() {
                let deps: Vec<String> =
                    pkg.dependencies.iter().map(|d| format!("\"{}\"", d)).collect();
                out.push_str(&format!("dependencies = [{}]\n", deps.join(", ")));
            }
            out.push('\n');
        }
        out
    }

    /// Read a lockfile from disk.
    pub fn read(path: &Path) -> Result<Self, String> {
        let content =
            fs::read_to_string(path).map_err(|e| format!("cannot read lockfile: {}", e))?;
        Self::parse(&content)
    }

    /// Write lockfile to disk.
    pub fn write(&self, path: &Path) -> Result<(), String> {
        let content = self.to_toml();
        fs::write(path, content).map_err(|e| format!("cannot write lockfile: {}", e))?;
        Ok(())
    }

    /// Check if lockfile is stale relative to forge.toml dependencies.
    /// Returns list of packages that need re-resolution.
    ///
    /// `current_deps` is a list of `(name, version_range)` pairs from forge.toml.
    pub fn check_staleness(&self, current_deps: &[(String, String)]) -> Vec<StaleDep> {
        let mut stale = Vec::new();

        // Build a map of locked package names -> versions for quick lookup
        let locked: std::collections::BTreeMap<&str, &str> = self
            .packages
            .iter()
            .map(|p| (p.name.as_str(), p.version.as_str()))
            .collect();

        // Build a map of current dep names -> ranges
        let current: std::collections::BTreeMap<&str, &str> = current_deps
            .iter()
            .map(|(n, r)| (n.as_str(), r.as_str()))
            .collect();

        // Check for missing or changed deps
        for (name, range) in &current {
            match locked.get(name) {
                None => {
                    stale.push(StaleDep::Missing {
                        name: name.to_string(),
                        range: range.to_string(),
                    });
                }
                Some(_locked_version) => {
                    // The lockfile stores a resolved version, not a range.
                    // A more sophisticated check would verify that the locked
                    // version still satisfies the range — for now we record
                    // that the dep exists and trust the lockfile until the
                    // manifest range text itself changes.
                }
            }
        }

        // Check for extra deps in lockfile that are no longer in forge.toml
        for pkg in &self.packages {
            if !current.contains_key(pkg.name.as_str()) {
                stale.push(StaleDep::Extra {
                    name: pkg.name.clone(),
                });
            }
        }

        stale
    }

    /// Find a locked package by name.
    pub fn find(&self, name: &str) -> Option<&LockedPackage> {
        self.packages.iter().find(|p| p.name == name)
    }
}

// ── Generation ──────────────────────────────────────────────────────

/// A resolved dependency ready to be recorded in the lockfile.
pub struct ResolvedDep {
    pub name: String,
    pub version: String,
    pub source: String,
    pub content_hash: String,
    pub artifact_hash: Option<String>,
    pub capabilities: Vec<String>,
    pub dependencies: Vec<String>,
}

/// Generate a new lockfile from resolved dependencies.
pub fn generate_lockfile(forge_version: &str, resolved: &[ResolvedDep]) -> Lockfile {
    // Use a fixed-format timestamp: YYYY-MM-DDThh:mm:ssZ
    // We avoid pulling in chrono — just read the system clock.
    let resolved_at = {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();
        format_timestamp(now)
    };

    let packages = resolved
        .iter()
        .map(|r| LockedPackage {
            name: r.name.clone(),
            version: r.version.clone(),
            source: r.source.clone(),
            content_hash: r.content_hash.clone(),
            artifact_hash: r.artifact_hash.clone(),
            capabilities: r.capabilities.clone(),
            dependencies: r.dependencies.clone(),
        })
        .collect();

    Lockfile {
        metadata: LockfileMetadata {
            forge_version: forge_version.to_string(),
            resolved_at,
        },
        packages,
    }
}

/// Format a Unix timestamp as ISO 8601 UTC (`YYYY-MM-DDThh:mm:ssZ`).
fn format_timestamp(secs: u64) -> String {
    // Simple UTC conversion without external crate.
    let days = secs / 86400;
    let time_of_day = secs % 86400;
    let hours = time_of_day / 3600;
    let minutes = (time_of_day % 3600) / 60;
    let seconds = time_of_day % 60;

    // Convert days since epoch to Y-M-D using a civil calendar algorithm.
    let (y, m, d) = civil_from_days(days as i64);

    format!(
        "{:04}-{:02}-{:02}T{:02}:{:02}:{:02}Z",
        y, m, d, hours, minutes, seconds
    )
}

/// Convert days since 1970-01-01 to (year, month, day).
/// Algorithm from Howard Hinnant's `civil_from_days`.
fn civil_from_days(z: i64) -> (i64, u32, u32) {
    let z = z + 719468;
    let era = if z >= 0 { z } else { z - 146096 } / 146097;
    let doe = (z - era * 146097) as u32;
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365;
    let y = yoe as i64 + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if m <= 2 { y + 1 } else { y };
    (y, m, d)
}

// ── Tests ───────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn roundtrip_empty_lockfile() {
        let lf = Lockfile {
            metadata: LockfileMetadata {
                forge_version: "0.1.0".to_string(),
                resolved_at: "2026-03-15T12:00:00Z".to_string(),
            },
            packages: vec![],
        };
        let toml_str = lf.to_toml();
        let parsed = Lockfile::parse(&toml_str).unwrap();
        assert_eq!(parsed.metadata.forge_version, "0.1.0");
        assert_eq!(parsed.metadata.resolved_at, "2026-03-15T12:00:00Z");
        assert!(parsed.packages.is_empty());
    }

    #[test]
    fn roundtrip_with_packages() {
        let lf = Lockfile {
            metadata: LockfileMetadata {
                forge_version: "0.1.0".to_string(),
                resolved_at: "2026-03-15T12:00:00Z".to_string(),
            },
            packages: vec![
                LockedPackage {
                    name: "http-client".to_string(),
                    version: "2.1.0".to_string(),
                    source: "registry".to_string(),
                    content_hash: "sha256:abc123".to_string(),
                    artifact_hash: Some("sha256:def456".to_string()),
                    capabilities: vec!["network".to_string()],
                    dependencies: vec![],
                },
                LockedPackage {
                    name: "graphql".to_string(),
                    version: "3.1.0".to_string(),
                    source: "registry".to_string(),
                    content_hash: "sha256:789".to_string(),
                    artifact_hash: None,
                    capabilities: vec!["network".to_string(), "native".to_string()],
                    dependencies: vec!["http-client".to_string()],
                },
            ],
        };

        let toml_str = lf.to_toml();
        let parsed = Lockfile::parse(&toml_str).unwrap();

        assert_eq!(parsed.packages.len(), 2);

        // Packages are sorted by name in output
        let graphql = parsed.find("graphql").unwrap();
        assert_eq!(graphql.version, "3.1.0");
        assert_eq!(graphql.capabilities, vec!["network", "native"]);
        assert_eq!(graphql.dependencies, vec!["http-client"]);

        let http = parsed.find("http-client").unwrap();
        assert_eq!(http.version, "2.1.0");
        assert_eq!(
            http.artifact_hash.as_deref(),
            Some("sha256:def456")
        );
    }

    #[test]
    fn staleness_detects_missing_dep() {
        let lf = Lockfile {
            metadata: LockfileMetadata {
                forge_version: "0.1.0".to_string(),
                resolved_at: "2026-03-15T12:00:00Z".to_string(),
            },
            packages: vec![],
        };

        let deps = vec![("new-pkg".to_string(), "^1.0".to_string())];
        let stale = lf.check_staleness(&deps);
        assert_eq!(stale.len(), 1);
        match &stale[0] {
            StaleDep::Missing { name, range } => {
                assert_eq!(name, "new-pkg");
                assert_eq!(range, "^1.0");
            }
            _ => panic!("expected Missing"),
        }
    }

    #[test]
    fn staleness_detects_extra_dep() {
        let lf = Lockfile {
            metadata: LockfileMetadata {
                forge_version: "0.1.0".to_string(),
                resolved_at: "2026-03-15T12:00:00Z".to_string(),
            },
            packages: vec![LockedPackage {
                name: "old-pkg".to_string(),
                version: "1.0.0".to_string(),
                source: "registry".to_string(),
                content_hash: "sha256:aaa".to_string(),
                artifact_hash: None,
                capabilities: vec![],
                dependencies: vec![],
            }],
        };

        let deps: Vec<(String, String)> = vec![];
        let stale = lf.check_staleness(&deps);
        assert_eq!(stale.len(), 1);
        match &stale[0] {
            StaleDep::Extra { name } => assert_eq!(name, "old-pkg"),
            _ => panic!("expected Extra"),
        }
    }

    #[test]
    fn generate_lockfile_creates_valid_toml() {
        let resolved = vec![
            ResolvedDep {
                name: "alpha".to_string(),
                version: "1.0.0".to_string(),
                source: "registry".to_string(),
                content_hash: "sha256:aaa".to_string(),
                artifact_hash: None,
                capabilities: vec![],
                dependencies: vec![],
            },
            ResolvedDep {
                name: "beta".to_string(),
                version: "2.0.0".to_string(),
                source: "git+https://example.com/beta@abc123".to_string(),
                content_hash: "sha256:bbb".to_string(),
                artifact_hash: Some("sha256:ccc".to_string()),
                capabilities: vec!["native".to_string()],
                dependencies: vec!["alpha".to_string()],
            },
        ];

        let lf = generate_lockfile("0.1.0", &resolved);
        assert_eq!(lf.metadata.forge_version, "0.1.0");
        assert_eq!(lf.packages.len(), 2);

        // Verify it round-trips through TOML
        let toml_str = lf.to_toml();
        let parsed = Lockfile::parse(&toml_str).unwrap();
        assert_eq!(parsed.packages.len(), 2);
        assert!(parsed.find("alpha").is_some());
        assert!(parsed.find("beta").is_some());
    }

    #[test]
    fn toml_output_is_deterministic() {
        let lf = Lockfile {
            metadata: LockfileMetadata {
                forge_version: "0.1.0".to_string(),
                resolved_at: "2026-03-15T12:00:00Z".to_string(),
            },
            packages: vec![
                LockedPackage {
                    name: "zebra".to_string(),
                    version: "1.0.0".to_string(),
                    source: "registry".to_string(),
                    content_hash: "sha256:zzz".to_string(),
                    artifact_hash: None,
                    capabilities: vec![],
                    dependencies: vec![],
                },
                LockedPackage {
                    name: "alpha".to_string(),
                    version: "1.0.0".to_string(),
                    source: "registry".to_string(),
                    content_hash: "sha256:aaa".to_string(),
                    artifact_hash: None,
                    capabilities: vec![],
                    dependencies: vec![],
                },
            ],
        };

        let toml1 = lf.to_toml();
        let toml2 = lf.to_toml();
        assert_eq!(toml1, toml2);

        // alpha should come before zebra regardless of input order
        let alpha_pos = toml1.find("name = \"alpha\"").unwrap();
        let zebra_pos = toml1.find("name = \"zebra\"").unwrap();
        assert!(alpha_pos < zebra_pos, "packages should be sorted by name");
    }

    #[test]
    fn parse_rejects_invalid_toml() {
        let result = Lockfile::parse("this is not valid toml {{{{");
        assert!(result.is_err());
    }

    #[test]
    fn timestamp_format() {
        // 2026-03-15 00:00:00 UTC = 1773532800
        let ts = format_timestamp(1773532800);
        assert_eq!(ts, "2026-03-15T00:00:00Z");
    }

    #[test]
    fn find_returns_none_for_missing() {
        let lf = Lockfile {
            metadata: LockfileMetadata {
                forge_version: "0.1.0".to_string(),
                resolved_at: "2026-03-15T12:00:00Z".to_string(),
            },
            packages: vec![],
        };
        assert!(lf.find("nonexistent").is_none());
    }
}
